### ISSUE TITLE
About Train

### ISSUE THREAD

**Issue by xyt000-xjj** [sony/san#1]
May I ask if you could provide the training command? Thank you very much.

**Comment by yahshibu** [comment]
Thank you very much for having an interest in our work.

This repository doesn't include .py files required for training. You can't execute it even if you know the training command. We're planning to add our training code after we get accepted to a conference. Sorry for the inconvenience.

Best regards.

**Comment by TakashiShibuyaSony** [comment]
We released our training code. Please check README.md. Thank you.
