### ISSUE TITLE
About out_fun, out_dir of simple-san

### ISSUE THREAD

**Issue by henomoto1025** [sony/san#4]
I have a question regarding the implementation of discriminator loss in the simple-san example.
According to Appendix B of the SAN paper, two discriminator outputs are defined: `out_fun`, where the direction vector is detached, and `out_dir`, where the intermediate feature is detached. Then `out_fun` is used for hinge loss, and `out_dir` is used for WGAN loss.

However, it appears that `out_fun` and `out_dir` are reversed in the current implementation of simple-san, as seen here:
https://github.com/sony/san/blob/44179007b5aa4899e6cbe5eb1316dc0903404a52/simple-san/models/discriminator.py#L50-L52

Am I missing something, or is there an error in the implementation?

**Comment by ytakida** [comment]
Thank you for carefully checking our code and pointing out the error.

Your observation is correct, and the implementaion had the error. `out_fun` and `out_dir` should be calculated with detached `direction` and `h_feature`, respectively (as stated in Appendix B). We have reflected this modification in the corresponding part of the simple-san implementation accordingly.

We really appreciate your carefull review and notification!

**Comment by henomoto1025** [comment]
Thank you for the prompt clarification and for addressing the issue so quickly. I'm glad to have been able to contribute to the improvement of the project!
